{{
    config(
        materialized='table',
        
        tags=['platform_demo', 'dimension']
    )
}}

{#
    ════════════════════════════════════════════════════════════════════════════
    DIMENSION: dim_demo_test
    ════════════════════════════════════════════════════════════════════════════
    
    Generated by Platform Entity Designer
    Created: 2026-01-21T15:15:27.834Z
    
    This model uses the Platform Entity pattern which automatically injects
    control fields based on the entity type (dimension).
    
    ════════════════════════════════════════════════════════════════════════════
#}

{{ platform_entity(
    entity_type='dimension',
    primary_key='customer_id'
) }}

SELECT
    email,
    address_line1,
    city

FROM {{ ref('raw_customers') }}

{{ platform_entity_end() }}
